# Lumo UI Plugin
# This file is used to store configurations for the Lumo UI Plugin
# Do not delete this file

ThemeName=AppTheme2
ComponentsDir=core/ui-components/src/commonMain/kotlin/app/sigot/core/ui/components
# Windows: ComponentsDir=ui-components\src\main\java\com\nomanr\ui_components
PackageName=app.sigot.core.ui.components
KotlinMultiplatform=true