# Lumo UI Plugin
# This file is used to store configurations for the Lumo UI Plugin
# Do not delete this file

ThemeName=AppTheme2
ComponentsDir=core/ui-components/src/commonMain/kotlin/app/sigot/core/ui
PackageName=app.sigot.core.ui
KotlinMultiplatform=true