name: Deploy Staging API

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/api/worker/**"
      - "core/**"
      - "buildLogic/**"
      - "gradle/**"
      - "gradle.properties"
      - "settings.gradle.kts"

jobs:
  verify:
    name: "Deploy"
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: setup-java
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Initialize
        run: ./sigo api:worker init

      - name: Deploy to Cloudflare
        run: ./sigo api:worker deploy --env staging
        env:
          APP_BACKEND_URL: staging.${{ vars.APP_BACKEND_URL }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
